<a href="https://colab.research.google.com/github/YuthikaKhedwal/python/blob/main/T%26TLAB5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np 
from numpy import random

def reshape() :
  if(n < 4) :
    print("Cannot be reshaped in pxq")
  else :
    for i in range(n):
      for j in range(n) :
        if(i*j == n) :
          print(arr.reshape(i,j))
          return
    print("Cannot be reshaped in pxq")

n = (int)(input("Enter no of ele: "))
arr = np.random.randint(1,10,n)
print(arr)
reshape()
print("YUTHIKA KHEDWAL,1906150")

Enter no of ele: 9
[6 2 6 6 4 6 8 1 5]
[[6 2 6]
 [6 4 6]
 [8 1 5]]
YUTHIKA KHEDWAL,1906150


In [14]:
import numpy as np
n=int(input('enter value of n'))
arr1=np.random.randint(1,50,(n,n))
print(arr1)
arr2=np.random.randint(1,50,(n,n))
print(arr2)
mnp=arr1@arr2
print(mnp)
mnpt=np.matrix.transpose(mnp)
r=mnp@mnpt
i=np.identity(n,dtype='int')

comp=r==i
result=comp.all()
print(result)
print("YUTHIKA KHEDWAL,1906150")

enter value of n3
[[18 48 43]
 [49  1 28]
 [34 46 42]]
[[42 29 39]
 [15 11 35]
 [28  5 23]]
[[2680 1265 3371]
 [2857 1572 2590]
 [3294 1702 3902]]
False
YUTHIKA KHEDWAL,1906150


In [13]:
import numpy as np
m=int(input("Enter M:-"))
n=int(input("Enter N:-"))
matrix_A = []
for i in range(m):
  row_A = []
  for j in range(n):
    element=int(input())
    row_A.append(element)
  matrix_A.append(row_A)
print(matrix_A)
matrix_A=np.array(matrix_A)
matrix_A=matrix_A.reshape(m,n)

a=[]
for i in range(0,2):
    print("enter number at index",i)
    item=int(input("enter the column vector:"))
    a.append(item)
arr2=np.array(a)
arr2=arr2.reshape(n,1)
print(arr2)
print("dot products")
for i in range(m):
    sub=matrix_A[0:n,i]
    print(np.dot(sub,arr2),end=" ")
    print("YUTHIKA KHEDWAL,1906150")

Enter M:-2
Enter N:-2
1
2
3
4
[[1, 2], [3, 4]]
enter number at index 0
enter the column vector:2
enter number at index 1
enter the column vector:2
[[2]
 [2]]
dot products
[8] YUTHIKA KHEDWAL,1906150
[12] YUTHIKA KHEDWAL,1906150
